spring:
  application:
    name: send-email-html
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      globally_quoted_identifiers: true
  mail:
    transport:
      protocol: smtp
    smtp:
      writetimeout: 10000
      connectiontimeout: 10000
      timeout: 10000
      auth: true
      starttls:
        enable: true
        required: true
    mime:
      charset: UTF